// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzkyxlihetwvsgxqymas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6a3l4bGloZXR3dnNneHF5bWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODU1NzksImV4cCI6MjA3MTM2MTU3OX0.JXt4E__DCBrUXcO_iIThPST_FB9xkJaQZTLCipvYk9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});